var $=jQuery;$(document).ready(function(){$(".dropdown-toggle").click(function(event){if(!$(event.target).hasClass("dropdown-icon")){var url=$(this).attr('href');window.location=url;return!1}});$('#bs4navbar ul li').hover(function(){if($(window).width()>768){$(this).children('.dropdown-menu').stop(!0,!1,!0).addClass('show')}},function(){if($(window).width()>768){$(this).children('.dropdown-menu').stop(!0,!1,!0).removeClass('show')}});$(function(){$('#bs4navbar').on('shown.bs.collapse',function(){$('#navbar-burger').addClass('hidden');$('#navbar-close').removeClass('hidden');$('#navbar__rs').removeClass('hidden')}).on('hidden.bs.collapse',function(){$('#navbar-burger').removeClass('hidden');$('#navbar-close').addClass('hidden');$('#navbar__rs').addClass('hidden')})});$(window).scroll(function(){$(".site-header").toggleClass("smaller",$(this).scrollTop()>50)})});$(window).resize(function(){$('#bs4navbar ul li').children('.dropdown-menu').stop(!0,!1,!0).removeClass('show')})
$("* [style]").removeAttr("style");jQuery(document).ready(function($){$('.sun').each(function(){var sun=$(this);var link=$(this).find('a[data-sun-link]');link.each(function(){var dataLink=$(this).data('sun-link');if(dataLink!="partner"&&dataLink!="unistra"){sun.find('a[data-sun-link="'+dataLink+'"]').hover(function(){sun.find('a[data-sun-link="'+dataLink+'"]').addClass('sun-hover')},function(){sun.find('a[data-sun-link="'+dataLink+'"]').removeClass('sun-hover')})}})})});$(document).ready(function(){$('.blog-post-categories__list').select2({placeholder:'Filter by category',theme:"classic",dropdownCssClass:'blog__filters'});$('.blog-post-categories__list').on('change',function(){window.location=$(this).find('option:selected').attr('data-url')})});function scrollToDiv(element){element=element.replace("link","");$('html,body').unbind().animate({scrollTop:$(element).offset().top-90},'slow')};$(document).ready(function(){$("#t1,.time1").click(function(){$("#arrow").removeClass("t2-arrow t3-arrow t4-arrow");$("#arrow").addClass("t1-arrow");$(".study_option_0,#fleche-droite").show();$(".study_option_1,.study_option_2,.study_option_3,#fleche-gauche").hide()
$(".time1").css("background-color","rgb(236, 184, 82)");$(".time2,.time3,.time4").css("background-color","white");$("#fleche-gauche").hide();currentIndex=0});$("#t2,.time2").click(function(){$("#arrow").removeClass("t1-arrow t3-arrow t4-arrow");$("#arrow").addClass("t2-arrow");$(".study_option_1,#fleche-droite,#fleche-gauche").show();$(".study_option_0,.study_option_2,.study_option_3").hide()
$(".time2").css("background-color","rgb(236, 184, 82)");$(".time1,.time3,.time4").css("background-color","white");$("#fleche-gauche").show();currentIndex=1});$("#t3,.time3").click(function(){$("#arrow").removeClass("t1-arrow t2-arrow t4-arrow");$("#arrow").addClass("t3-arrow");$(".study_option_2,#fleche-droite,#fleche-gauche").show();$(".study_option_0,.study_option_1,.study_option_3").hide()
$(".time3").css("background-color","rgb(236, 184, 82)");$(".time1,.time2,.time4").css("background-color","white");$("#fleche-gauche").show();currentIndex=2});$("#t4,.time4").click(function(){$("#arrow").removeClass("t1-arrow t2-arrow t3-arrow");$("#arrow").addClass("t4-arrow");$(".study_option_3,#fleche-droite").show();$(".study_option_0,.study_option_2,.study_option_1,#fleche-gauche").hide()
$(".time4").css("background-color","rgb(236, 184, 82)");$(".time1,.time3,.time2").css("background-color","white");$("#fleche-gauche").show();$("#fleche-droite").hide();currentIndex=3});var slides=$('.text-and-arrows').children('div')
var flecheGauche=$("#fleche-gauche");var flecheDroite=$("#fleche-droite");var currentIndex=-1;slides.each(function(){$(this).hide()});$(".time1").css("background-color","rgb(236, 184, 82)");loadPage(0);function loadPage(i){flecheDroite.show()
flecheGauche.show()
if(slides[i]){$(slides[i]).show();if($(slides[i])[0].className==='study_option_3'){flecheDroite.hide()}
if($(slides[i])[0].className==='study_option_0'){flecheGauche.hide()}}else{return}
if(slides[currentIndex]){$(slides[currentIndex]).hide()}
currentIndex=i}
flecheDroite.click(function(){$('#button-time').children().css('background-color','white')
$(".time"+(currentIndex+2)).css("background-color","rgb(236, 184, 82)");$("#arrow").removeClass("t1-arrow t2-arrow t3-arrow t4-arrow");$("#arrow").addClass("t"+(currentIndex+2)+"-arrow");loadPage(currentIndex+1)})
flecheGauche.click(function(){$('#button-time').children().css('background-color','white')
$(".time"+currentIndex).css("background-color","rgb(236, 184, 82)");$("#arrow").removeClass("t1-arrow t2-arrow t3-arrow t4-arrow");$("#arrow").addClass("t"+currentIndex+"-arrow");loadPage(currentIndex-1)})})